# LaTeXmk configuration file
# This shows how to use lualatex (http://en.wikipedia.org/wiki/LuaTeX)
# with latexmk.  
#
#   WARNING: The method shown here is suitable only for ver. 4.51 and
#            later of latexmk, not for earlier versions.
#
$pdflatex = 'lualatex --interaction=nonstopmode --shell-escape --synctex=1';
$pdf_mode = 4;
$postscript_mode = $dvi_mode = 0;


